### ISSUE TITLE
Possible interest to Xbox 360 Live game '1 vs. 100'

### ISSUE THREAD

**Issue by ShitfacedKass** [x1nixmzeng/project-grabbed#1]
Hey!

I am currently looking into the files of the defunct Xbox Live game '1 vs. 100', and I've noticed that some of the files seem to be encrypted via a method similar to Rare games. Each file has a heading `CAFF07.08.06.0036`, just like Viva Piñata and Banjo-Kazooie: Nuts & Bolts. Perhaps there could be some common interest into this?

You can find two versions of the game here:
https://archive.org/details/1Vs1002.0.1167.0.02Dec072009
https://archive.org/details/1Vs1002.0.1317.0.0220100414.7z

All files that contain the heading seem to be in the 'set' folder, probably where the models, textures, some audio clips, etc. are stored.

**Comment by x1nixmzeng** [comment]
Hey, thanks for reaching out - I was not aware of this game using the same format - my assumption was this was a format used by Rare (it seems more like a Microsoft Studios format).

The CAFF files are containers for data formats, in the game there looks to be animations (`.anim.bin`), fonts (`.ttf.bin`), and models (`.mb.bin`). Audio uses the Xbox wavebanks (`.xwb`).

I will take a look at the model format but I can make no promises, as this project was focused on earlier games.

**Comment by ShitfacedKass** [comment]
Hey!

Just coming around to ask – have you had any luck unpacking those files or somehow dealing with them?

I noticed there was a commit related to it, but I'm having a little trouble using the updated tools – never really worked with C++ in this kind of fashion, so therefore I'm having a few difficulties.

If it's not too difficult and annoying, could you explain how to use them, please?
Sorry for being thick!

**Comment by x1nixmzeng** [comment]
I did some research and it does use a similar format. My interest is in understanding the data structure and I added code that extracts the texture data.

The code is a shared library - I should have added a tool too.

What data are you interested in with this game? The models are Xbox avatars and scenery? The game has a few lua scripts that don't need extracting, and the audio are standard wavebanks

**Comment by ShitfacedKass** [comment]
I'm mainly looking for texture files, as the game contains quite a few high-resolution textures that I'd be interested in repurposing for my own personal project – but any available data would be fine!

I didn't find any tool associated with the library, which is probably why I wasn't able to do anything. Am I missing something or is the tool simply not available yet?

**Comment by x1nixmzeng** [comment]
GitHub now builds the project, so now you can download from here:
https://github.com/x1nixmzeng/project-grabbed/actions/runs/826056336

There is now a tool to dump textures "onevs_app". Download the artifacts zip, extract it, and drag a `.mb.bin` file from the "sets" folder of your "1 vs 100" copy of the game to it - it will dump out PNG files using their original names.

It doesn't keep any mipmaps but you do the highest quality image

**Comment by ShitfacedKass** [comment]
Ah, I see, thank you very much!

I think I've got everything I needed, but I did notice that, curiously, no HUD elements appear whatsoever (which is probably to be expected, I suppose, since they'd probably not be in the 'set' folder), but I kinda struggle to see where they'd be stored instead. Just out of curiousness, do you have any ideas?

Anyways, thank you very very much for your work with this game, I extremely appreciate your efforts on this – you're an absolute star!

**Comment by x1nixmzeng** [comment]
I added a new tool to dump xzp files for the the HUD elements - there is `launch.xzp` and `startuppkg.xzp`

One of those files has a "compressed" PNG folder that I have no idea about - and there's a lot of generic Xbox looking string and layout files that I won't bother with

**Comment by x1nixmzeng** [comment]
Closing as game support has been added!
